### ISSUE TITLE
Feature Request: Ability to remap Fn+<key> combos

### ISSUE THREAD

**Issue by ReK42** [zllovesuki/G14Manager#12]
The Fn key cannot be detected by AutoHotkey to be used for key combos (e.g. Fn+Left=Home, Fn+Right=End). I am unsure whether the Fn keypress can be detected by the Asus ACPI driver or if it is implemented completely within the keyboard hardware. If it can be detected, being able to map such key combos in ROG Manager would be an excellent feature.

**Comment by zllovesuki** [comment]
Unfortunately they are not detected via the Asus ACPI driver. If you run with `.\run.ps1` and try to press those combos, they won't show up as part of the ACPI notifications from ATK.

"Fn +<Key>" combo are not processed by the OS but by the underlying hardware, and sent as a combo key. Asus's driver interprets their defined key presses, which is why we can receive it in the OS. I think this is getting into Windows Driver territory and we need to write a driver to interpret those key combos.

**Comment by zllovesuki** [comment]
However, it _may_ be possible to according to this: https://superuser.com/questions/65/remap-fn-to-another-key

**Comment by zllovesuki** [comment]
I have some good news 😊

https://github.com/zllovesuki/ROGManager/blob/keyboard/reverse_eng.md

It turns out, the key combo code for `Fn+Left` (0xb2) and `Fn+Right` (0xb3) are actually sent over USB device as raw buffer. However, it doesn't seem like Asus Optimization handles them. I may be able to write something with `libusb` in C to capture those input.

**Comment by zllovesuki** [comment]
Okay, I actually did it. ROGManager now directly reads from keyboard's special combo key, and it can read Fn+Left and Fn+Right. I shall release the next version to custom those keys.

**Comment by edkozuto** [comment]
It would also be nice to include a FN+mapper, for adding PgUp/Dn or Home/End without any AutoHotKey stuff.
Great job anyway, will try to build tomorrow.

**Comment by zllovesuki** [comment]
Hello, would you mind trying out v0.1.3 (once CI/CD finishes building) for the experimental features of remapping Fn+Left/Right to PgUp/PgDown?

Enable with `-experimental` flag, such as `.\ROGManager.exe -experimental`.

Reason why this is behind an experimental flag: this locks the goroutine to the OS thread to invoke C code, and I'm not sure if this stable enough yet.
