### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by jcastilloalonso** [zllovesuki/G14Manager#51]
Hey Rachel,

I found your application and wanted to congratulate you for your work.

I've been using [atrofac](https://github.com/cronosun/atrofac) and [G14ControlR3](https://github.com/aredden/G14ControlR3). atrofac seems like development has stalled, it has some outstanding issues and while it works, it's bound to have more problems in the future.

G14ControlR3 uses atrofac plus incorporates multiple new features like TDP control and Boost settings to lower heat generation.

Ideally it would rock to have one app to rule them all, so adding G14ControlR3 features to your application would be great to simplify the number of applications to run.

Do you have any plans to add a little bit of GUI to modify and set parameters?

Thanks again for your time in this application!

**Comment by zllovesuki** [comment]
I'm actually thinking about how to implement an GUI to modify and set parameters. However, I don't have a lot of experience wrt writing GUI applications on Windows, so I'm planning on making a console interface where you can adjust the parameters. This will come soon once I figure out some other design decisions.

Regarding TDP control and Boost settings:
Boost: Yes it can be done, but I recommend making this as your Power Plan instead of having G14Manager to change that setting for you, as Power Plan already has the option for that. It will just be a new profile in G14Manager (once I release the version with customizable profiles that would be easy to use).
TDP: Unfortunately I'm not very keen on integrating this. Even in my usage, I found the heat generation to be fine with the default settings, and I personally don't see much values with fiddling TDP. That's my personal opinion.
Beside the that, TDP controls requires access to Ring0 (via [RyzenAdj](https://github.com/FlyGoat/RyzenAdj) and [WinRing0](https://github.com/QCute/WinRing0)). I don't think that's something that I want to do.

**Comment by jcastilloalonso** [comment]
Agree with your sentiment around both issues, I tend to keep my settings very basic (don't overengineer something)

Can't wait to see some form of GUI for parameters, I'm pretty used to CLI so that's doesn't scare me at all.

Thanks again.
